version: '3'
services:
  mysql-db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 3570951
      MYSQL_DATABASE: floricultura
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
